{
    parserClass="com.github.privatech.minimessage.parser.MiniMessageParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="MiniMessage"
    psiImplClassSuffix="Impl"
    psiPackage="com.github.privatech.minimessage.psi"
    psiImplPackage="com.github.privatech.minimessage.psi.impl"

    elementTypeHolderClass="com.github.privatech.minimessage.psi.MiniMessageTypes"
    elementTypeClass="com.github.privatech.minimessage.psi.MiniMessageElementType"
    tokenTypeClass="com.github.privatech.minimessage.psi.MiniMessageTokenType"

    tokens=[
        COLON=":"
        LT="<"
        GT=">"
        SLASH="/"
        ESCAPE="\\"

        plainText="[^<]*"
        string="regexp:\"[\u0000-\uFFFF(\\\")]*\"|'[\u0000-\uFFFF(\\')]*'"
        tagName="regexp:[!?#]?[a-zA-Z0-9_-]*"
    ]
}

root ::= content

content ::= plainText tag content? | plainText

tag ::= tagStart content* tagEnd? | autoClosedTag

autoClosedTag ::= LT tagName tagArgument? SLASH GT
tagStart ::= LT tagName tagArgument? GT
tagEnd ::= LT SLASH tagName GT

tagArgument ::= COLON argumentType tagArgument?
argumentType ::= string | tagName
