name: Publish Plugin
on:
  release:
    types:
      - published
jobs:
  build-sign-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set Patch notes
        run: ./gradlew patchPluginXml -PchangeNotes=${{ github.event.release.body }}

      - name: Build with Gradle
        run: ./gradlew buildPlugin

      - name: Sign plugin
        run: >
          ./gradlew signPlugin
          -PprivateKey=${{ secrets.PRIVATE_KEY }} 
          -PcertificateChain=${{ secrets.CERTIFICATE_CHAIN }} 
          -Ppassword=${{ secrets.PRIVATE_KEY_PASSWORD }}

      - name: Publish plugin
        run: ./gradlew publishPlugin -Ptoken=${{ secrets.MARKETPLACE_TOKEN }}